image: Visual Studio 2017
configuration: Release

platform:
  - x64
  - x86

install:
  - ps: Install-Product node 11 $env:platform
  - npm install
  - curl -L -o nasminst.exe https://www.nasm.us/pub/nasm/releasebuilds/2.14/win32/nasm-2.14-installer-x86.exe
  - start /wait nasminst.exe /S
  - ps: $env:path="C:\Program Files (x86)\nasm;$($env:path)"

build_script:
  - npm run download
  - npm run build
  - npm run package

test: off

artifacts:
  - path: packages/*.zip
  - path: packages/*.7z

# do not build on tags
skip_tags: true
